### ISSUE TITLE
Shortcut does not work

### ISSUE THREAD

**Issue by bramvbilsen** [telekommander/hyper-systray#1]
I installed the plugin and I am using the default config:
```
    systray: {
        hotkey: "Ctrl+Space"
    },
```
The icon is there but the shortcut does not work. Using the overlay plugin, it does work. Any idea what the issue might be? (Running hyper 2.0.0)

**Comment by DanielTamkin** [comment]
Getting the exact same problem. @telekommander has this project's development been halted?

**Comment by vlrmprjct** [comment]
Guys, sorry i am late.

What Plugins you are using ?
Another shortcut or the default-shortcut (Alt+Space ) is working ?

**Comment by aridokmecian** [comment]
I am also having the same issue, Alt Space works but I have another program using that shortcut and I want to change the one for this plugin but its does not seem to make a difference.

**Comment by vlrmprjct** [comment]
@aridokmecian , 
May that is not possible. Try changing the shortcut of the other program before hyper.js is loaded.

And if the shortcut has been changed in the hyper-config, hyper.js must be restarted to (re-)register the new shortcut.

**Comment by aridokmecian** [comment]
I found a solution to my problem, I was placing the config for the plugin under the plugins array in the .hyper file, I moved the config to the top of the file and it solved my problem!
